/*
 * Microsoft Bot Connector API - v3.0
 *
 * The Bot Connector REST API allows your bot to send and receive messages to channels configured in the  [Bot Framework Developer Portal](https://dev.botframework.com). The Connector service uses industry-standard REST  and JSON over HTTPS.    Client libraries for this REST API are available. See below for a list.    Many bots will use both the Bot Connector REST API and the associated [Bot State REST API](/en-us/restapi/state). The  Bot State REST API allows a bot to store and retrieve state associated with users and conversations.    Authentication for both the Bot Connector and Bot State REST APIs is accomplished with JWT Bearer tokens, and is  described in detail in the [Connector Authentication](/en-us/restapi/authentication) document.    # Client Libraries for the Bot Connector REST API    * [Bot Builder for C#](/en-us/csharp/builder/sdkreference/)  * [Bot Builder for Node.js](/en-us/node/builder/overview/)  * Generate your own from the [Connector API Swagger file](https://raw.githubusercontent.com/Microsoft/BotBuilder/master/CSharp/Library/Microsoft.Bot.Connector.Shared/Swagger/ConnectorAPI.json)    © 2016 Microsoft
 *
 * API version: v3
 * Contact: botframework@microsoft.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package botbuilder

import (
	"errors"
)

// AttachmentsApiService is a service that implents the logic for the AttachmentsApiServicer
// This service should implement the business logic for every endpoint for the AttachmentsApi API. 
// Include any external packages or services that will be required by this service.
type AttachmentsApiService struct {
}

// NewAttachmentsApiService creates a default api service
func NewAttachmentsApiService() AttachmentsApiServicer {
	return &AttachmentsApiService{}
}

// AttachmentsGetAttachment - GetAttachment
func (s *AttachmentsApiService) AttachmentsGetAttachment(attachmentId string, viewId string) (interface{}, error) {
	// TODO - update AttachmentsGetAttachment with the required logic for this service method.
	// Add api_attachments_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'AttachmentsGetAttachment' not implemented")
}

// AttachmentsGetAttachmentInfo - GetAttachmentInfo
func (s *AttachmentsApiService) AttachmentsGetAttachmentInfo(attachmentId string) (interface{}, error) {
	// TODO - update AttachmentsGetAttachmentInfo with the required logic for this service method.
	// Add api_attachments_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'AttachmentsGetAttachmentInfo' not implemented")
}
